name: Simple CI Test - V3

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - feature/*


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Simulate environment check
      run: |
        echo "Checking for required files..."
        if [ -f README.md ]; then
          echo "README exists. âœ…"
        else
          echo "README missing! âŒ"
          exit 1
        fi


    - name: Run test
      run: |
        echo "This is your first pipeline, Or!"
        echo "CI is working. Let's gooo ğŸ’¥"

    - name: Deploy (simulated)
      if: success()  # Only runs if earlier steps succeeded
      run: |
        echo "ğŸ¯ CI passed. Deploying to production..."
        echo "âœ… Code deployed successfully (simulated)"
